### ISSUE TITLE
devenv new: !var: unbound variable

### ISSUE THREAD

**Issue by matjack1** [endorama/devenv#1]
When I run `devenv new` I get

```
~/.devenv/libs/config.sh: line 8: !var: unbound variable
```

I'm using ZSH and OhMyZsh on Ubuntu 18.04. Bash version 4.4.19.

Do you know what's going on?

**Comment by endorama** [comment]
I tried this today and is properly working for me.

What OS, shell and shell version are you using?

My tests have been done on Ubuntu 16.04, `zsh 5.1.1 (x86_64-ubuntu-linux-gnu)`

**Comment by endorama** [comment]
Sorry for the late reply. I found the problem, there is no `profiles` defined in the devenv configuration file, thus `var` variable is unbound ( and the script properly breaks :P ).

PR #3 is ready for testing, could you let me know if it fixes the problem?
